### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [artyusmirnov/courseFinalTask#3]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by artyusmirnov** [comment]
В фиче удаления документов нужно делать проверку, есть ли документы в списке перед удалением и после, или просто удалить?

**Comment by artyusmirnov** [comment]
Во всех трех реализованных фичах использовал шаг "подготавливаю начальные данные", который загружал номенклатуру и контрагентов. Первым я его реализовал в фиче удаления документов и к остальным он подтягивался автоматически но с ошибкой ("шаг уже реализован..."). Наверное, имеет смысл вынести его в отдельную фичу?

**Comment by alehinsasha** [comment]
> Во всех трех реализованных фичах использовал шаг "подготавливаю начальные данные", который загружал номенклатуру и контрагентов. Первым я его реализовал в фиче удаления документов и к остальным он подтягивался автоматически но с ошибкой ("шаг уже реализован..."). Наверное, имеет смысл вынести его в отдельную фичу?

Совершенное верно! Эти шаги, т.е. фичи с такими шагами мы выносим в отдельные каталоги внутри каталога `\features` и воспринимаем (называем) библиотечными.

**Comment by alehinsasha** [comment]
> В фиче удаления документов нужно делать проверку, есть ли документы в списке перед удалением и после, или просто удалить?

Предлагаю на следующей неделе вернуться к этому вопросу?

**Comment by alehinsasha** [comment]
Задачу закрою, НО с удалением документов ещё позанимаемся.

**Comment by artyusmirnov** [comment]
> Предлагаю на следующей неделе вернуться к этому вопросу?

я только за

**Comment by alehinsasha** [comment]
ок! "пните" меня +/- в среду)
